language: cpp
compiler: g++-8

os: linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-8

script:
    - make
    - sudo make install
    - ./cp-tools -v
    - ./cp-run_tests

after_sucess:
    - echo "Success"

after_failure:
    - echo "Failure"
